# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(CMAKE_COMMAND) -E cmake_progress_start "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess/CMakeFiles" "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess/src/tests//CMakeFiles/progress.marks"
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/tests/all
	$(CMAKE_COMMAND) -E cmake_progress_start "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/tests/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/tests/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/tests/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/tests/CMakeFiles/tests.dir/rule:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/tests/CMakeFiles/tests.dir/rule
.PHONY : src/tests/CMakeFiles/tests.dir/rule

# Convenience name for target.
tests: src/tests/CMakeFiles/tests.dir/rule
.PHONY : tests

# fast build rule for target.
tests/fast:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

testBoardStatus.o: testBoardStatus.cpp.o
.PHONY : testBoardStatus.o

# target to build an object file
testBoardStatus.cpp.o:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testBoardStatus.cpp.o
.PHONY : testBoardStatus.cpp.o

testBoardStatus.i: testBoardStatus.cpp.i
.PHONY : testBoardStatus.i

# target to preprocess a source file
testBoardStatus.cpp.i:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testBoardStatus.cpp.i
.PHONY : testBoardStatus.cpp.i

testBoardStatus.s: testBoardStatus.cpp.s
.PHONY : testBoardStatus.s

# target to generate assembly for a file
testBoardStatus.cpp.s:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testBoardStatus.cpp.s
.PHONY : testBoardStatus.cpp.s

testDecodeCoordinates.o: testDecodeCoordinates.cpp.o
.PHONY : testDecodeCoordinates.o

# target to build an object file
testDecodeCoordinates.cpp.o:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testDecodeCoordinates.cpp.o
.PHONY : testDecodeCoordinates.cpp.o

testDecodeCoordinates.i: testDecodeCoordinates.cpp.i
.PHONY : testDecodeCoordinates.i

# target to preprocess a source file
testDecodeCoordinates.cpp.i:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testDecodeCoordinates.cpp.i
.PHONY : testDecodeCoordinates.cpp.i

testDecodeCoordinates.s: testDecodeCoordinates.cpp.s
.PHONY : testDecodeCoordinates.s

# target to generate assembly for a file
testDecodeCoordinates.cpp.s:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testDecodeCoordinates.cpp.s
.PHONY : testDecodeCoordinates.cpp.s

testDecodePieceName.o: testDecodePieceName.cpp.o
.PHONY : testDecodePieceName.o

# target to build an object file
testDecodePieceName.cpp.o:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testDecodePieceName.cpp.o
.PHONY : testDecodePieceName.cpp.o

testDecodePieceName.i: testDecodePieceName.cpp.i
.PHONY : testDecodePieceName.i

# target to preprocess a source file
testDecodePieceName.cpp.i:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testDecodePieceName.cpp.i
.PHONY : testDecodePieceName.cpp.i

testDecodePieceName.s: testDecodePieceName.cpp.s
.PHONY : testDecodePieceName.s

# target to generate assembly for a file
testDecodePieceName.cpp.s:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testDecodePieceName.cpp.s
.PHONY : testDecodePieceName.cpp.s

testGetPieceInSquare.o: testGetPieceInSquare.cpp.o
.PHONY : testGetPieceInSquare.o

# target to build an object file
testGetPieceInSquare.cpp.o:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testGetPieceInSquare.cpp.o
.PHONY : testGetPieceInSquare.cpp.o

testGetPieceInSquare.i: testGetPieceInSquare.cpp.i
.PHONY : testGetPieceInSquare.i

# target to preprocess a source file
testGetPieceInSquare.cpp.i:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testGetPieceInSquare.cpp.i
.PHONY : testGetPieceInSquare.cpp.i

testGetPieceInSquare.s: testGetPieceInSquare.cpp.s
.PHONY : testGetPieceInSquare.s

# target to generate assembly for a file
testGetPieceInSquare.cpp.s:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testGetPieceInSquare.cpp.s
.PHONY : testGetPieceInSquare.cpp.s

testIsColumnClogged.o: testIsColumnClogged.cpp.o
.PHONY : testIsColumnClogged.o

# target to build an object file
testIsColumnClogged.cpp.o:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsColumnClogged.cpp.o
.PHONY : testIsColumnClogged.cpp.o

testIsColumnClogged.i: testIsColumnClogged.cpp.i
.PHONY : testIsColumnClogged.i

# target to preprocess a source file
testIsColumnClogged.cpp.i:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsColumnClogged.cpp.i
.PHONY : testIsColumnClogged.cpp.i

testIsColumnClogged.s: testIsColumnClogged.cpp.s
.PHONY : testIsColumnClogged.s

# target to generate assembly for a file
testIsColumnClogged.cpp.s:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsColumnClogged.cpp.s
.PHONY : testIsColumnClogged.cpp.s

testIsCoordinateValid.o: testIsCoordinateValid.cpp.o
.PHONY : testIsCoordinateValid.o

# target to build an object file
testIsCoordinateValid.cpp.o:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsCoordinateValid.cpp.o
.PHONY : testIsCoordinateValid.cpp.o

testIsCoordinateValid.i: testIsCoordinateValid.cpp.i
.PHONY : testIsCoordinateValid.i

# target to preprocess a source file
testIsCoordinateValid.cpp.i:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsCoordinateValid.cpp.i
.PHONY : testIsCoordinateValid.cpp.i

testIsCoordinateValid.s: testIsCoordinateValid.cpp.s
.PHONY : testIsCoordinateValid.s

# target to generate assembly for a file
testIsCoordinateValid.cpp.s:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsCoordinateValid.cpp.s
.PHONY : testIsCoordinateValid.cpp.s

testIsDiagonalClogged.o: testIsDiagonalClogged.cpp.o
.PHONY : testIsDiagonalClogged.o

# target to build an object file
testIsDiagonalClogged.cpp.o:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsDiagonalClogged.cpp.o
.PHONY : testIsDiagonalClogged.cpp.o

testIsDiagonalClogged.i: testIsDiagonalClogged.cpp.i
.PHONY : testIsDiagonalClogged.i

# target to preprocess a source file
testIsDiagonalClogged.cpp.i:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsDiagonalClogged.cpp.i
.PHONY : testIsDiagonalClogged.cpp.i

testIsDiagonalClogged.s: testIsDiagonalClogged.cpp.s
.PHONY : testIsDiagonalClogged.s

# target to generate assembly for a file
testIsDiagonalClogged.cpp.s:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsDiagonalClogged.cpp.s
.PHONY : testIsDiagonalClogged.cpp.s

testIsFrontClogged.o: testIsFrontClogged.cpp.o
.PHONY : testIsFrontClogged.o

# target to build an object file
testIsFrontClogged.cpp.o:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsFrontClogged.cpp.o
.PHONY : testIsFrontClogged.cpp.o

testIsFrontClogged.i: testIsFrontClogged.cpp.i
.PHONY : testIsFrontClogged.i

# target to preprocess a source file
testIsFrontClogged.cpp.i:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsFrontClogged.cpp.i
.PHONY : testIsFrontClogged.cpp.i

testIsFrontClogged.s: testIsFrontClogged.cpp.s
.PHONY : testIsFrontClogged.s

# target to generate assembly for a file
testIsFrontClogged.cpp.s:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsFrontClogged.cpp.s
.PHONY : testIsFrontClogged.cpp.s

testIsMoveClogged.o: testIsMoveClogged.cpp.o
.PHONY : testIsMoveClogged.o

# target to build an object file
testIsMoveClogged.cpp.o:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsMoveClogged.cpp.o
.PHONY : testIsMoveClogged.cpp.o

testIsMoveClogged.i: testIsMoveClogged.cpp.i
.PHONY : testIsMoveClogged.i

# target to preprocess a source file
testIsMoveClogged.cpp.i:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsMoveClogged.cpp.i
.PHONY : testIsMoveClogged.cpp.i

testIsMoveClogged.s: testIsMoveClogged.cpp.s
.PHONY : testIsMoveClogged.s

# target to generate assembly for a file
testIsMoveClogged.cpp.s:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsMoveClogged.cpp.s
.PHONY : testIsMoveClogged.cpp.s

testIsMoveValid.o: testIsMoveValid.cpp.o
.PHONY : testIsMoveValid.o

# target to build an object file
testIsMoveValid.cpp.o:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsMoveValid.cpp.o
.PHONY : testIsMoveValid.cpp.o

testIsMoveValid.i: testIsMoveValid.cpp.i
.PHONY : testIsMoveValid.i

# target to preprocess a source file
testIsMoveValid.cpp.i:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsMoveValid.cpp.i
.PHONY : testIsMoveValid.cpp.i

testIsMoveValid.s: testIsMoveValid.cpp.s
.PHONY : testIsMoveValid.s

# target to generate assembly for a file
testIsMoveValid.cpp.s:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsMoveValid.cpp.s
.PHONY : testIsMoveValid.cpp.s

testIsPieceNameValid.o: testIsPieceNameValid.cpp.o
.PHONY : testIsPieceNameValid.o

# target to build an object file
testIsPieceNameValid.cpp.o:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsPieceNameValid.cpp.o
.PHONY : testIsPieceNameValid.cpp.o

testIsPieceNameValid.i: testIsPieceNameValid.cpp.i
.PHONY : testIsPieceNameValid.i

# target to preprocess a source file
testIsPieceNameValid.cpp.i:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsPieceNameValid.cpp.i
.PHONY : testIsPieceNameValid.cpp.i

testIsPieceNameValid.s: testIsPieceNameValid.cpp.s
.PHONY : testIsPieceNameValid.s

# target to generate assembly for a file
testIsPieceNameValid.cpp.s:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsPieceNameValid.cpp.s
.PHONY : testIsPieceNameValid.cpp.s

testIsRowClogged.o: testIsRowClogged.cpp.o
.PHONY : testIsRowClogged.o

# target to build an object file
testIsRowClogged.cpp.o:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsRowClogged.cpp.o
.PHONY : testIsRowClogged.cpp.o

testIsRowClogged.i: testIsRowClogged.cpp.i
.PHONY : testIsRowClogged.i

# target to preprocess a source file
testIsRowClogged.cpp.i:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsRowClogged.cpp.i
.PHONY : testIsRowClogged.cpp.i

testIsRowClogged.s: testIsRowClogged.cpp.s
.PHONY : testIsRowClogged.s

# target to generate assembly for a file
testIsRowClogged.cpp.s:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testIsRowClogged.cpp.s
.PHONY : testIsRowClogged.cpp.s

testListValidMoves.o: testListValidMoves.cpp.o
.PHONY : testListValidMoves.o

# target to build an object file
testListValidMoves.cpp.o:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testListValidMoves.cpp.o
.PHONY : testListValidMoves.cpp.o

testListValidMoves.i: testListValidMoves.cpp.i
.PHONY : testListValidMoves.i

# target to preprocess a source file
testListValidMoves.cpp.i:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testListValidMoves.cpp.i
.PHONY : testListValidMoves.cpp.i

testListValidMoves.s: testListValidMoves.cpp.s
.PHONY : testListValidMoves.s

# target to generate assembly for a file
testListValidMoves.cpp.s:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testListValidMoves.cpp.s
.PHONY : testListValidMoves.cpp.s

testMove.o: testMove.cpp.o
.PHONY : testMove.o

# target to build an object file
testMove.cpp.o:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testMove.cpp.o
.PHONY : testMove.cpp.o

testMove.i: testMove.cpp.i
.PHONY : testMove.i

# target to preprocess a source file
testMove.cpp.i:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testMove.cpp.i
.PHONY : testMove.cpp.i

testMove.s: testMove.cpp.s
.PHONY : testMove.s

# target to generate assembly for a file
testMove.cpp.s:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/tests.dir/build.make src/tests/CMakeFiles/tests.dir/testMove.cpp.s
.PHONY : testMove.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tests"
	@echo "... testBoardStatus.o"
	@echo "... testBoardStatus.i"
	@echo "... testBoardStatus.s"
	@echo "... testDecodeCoordinates.o"
	@echo "... testDecodeCoordinates.i"
	@echo "... testDecodeCoordinates.s"
	@echo "... testDecodePieceName.o"
	@echo "... testDecodePieceName.i"
	@echo "... testDecodePieceName.s"
	@echo "... testGetPieceInSquare.o"
	@echo "... testGetPieceInSquare.i"
	@echo "... testGetPieceInSquare.s"
	@echo "... testIsColumnClogged.o"
	@echo "... testIsColumnClogged.i"
	@echo "... testIsColumnClogged.s"
	@echo "... testIsCoordinateValid.o"
	@echo "... testIsCoordinateValid.i"
	@echo "... testIsCoordinateValid.s"
	@echo "... testIsDiagonalClogged.o"
	@echo "... testIsDiagonalClogged.i"
	@echo "... testIsDiagonalClogged.s"
	@echo "... testIsFrontClogged.o"
	@echo "... testIsFrontClogged.i"
	@echo "... testIsFrontClogged.s"
	@echo "... testIsMoveClogged.o"
	@echo "... testIsMoveClogged.i"
	@echo "... testIsMoveClogged.s"
	@echo "... testIsMoveValid.o"
	@echo "... testIsMoveValid.i"
	@echo "... testIsMoveValid.s"
	@echo "... testIsPieceNameValid.o"
	@echo "... testIsPieceNameValid.i"
	@echo "... testIsPieceNameValid.s"
	@echo "... testIsRowClogged.o"
	@echo "... testIsRowClogged.i"
	@echo "... testIsRowClogged.s"
	@echo "... testListValidMoves.o"
	@echo "... testListValidMoves.i"
	@echo "... testListValidMoves.s"
	@echo "... testMove.o"
	@echo "... testMove.i"
	@echo "... testMove.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd "/run/media/francesco/3997c5e4-723d-463a-9aea-52fb76423e07/Varie/Sorgenti/miei/Progetti C++/Chess" && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

