name: "Build and run"
on:
  push:
    branches:     "master"
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
jobs:
  build-linux:
    name:    Build on linux
    runs-on: ubuntu-latest
    env:
      units:        board
      build_type:   Debug
      cpp_compiler: clang++
    steps:
    - uses:  actions/checkout@v4
    - name:  Set reusable strings
      id:    strings
      shell: bash
      run:   |
             echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    - name:  update catch2 repository
      run:   git clone https://github.com/catchorg/Catch2.git
    - name:  update chess repository
      run:   git clone https://github.com/antlampas/Chess.git
    - name:  Configure CMake
      run:   >
             cmake -B ${{ steps.strings.outputs.build-output-dir }}
             -DCMAKE_CXX_COMPILER=${{ env.cpp_compiler }}
             -DCMAKE_BUILD_TYPE=${{ env.build_type }}
             -DUNITS="$units"
             -S ${{ github.workspace }}
    - name:  Build
      run:   cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ env.build_type }}
    - name:  Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run:  ctest --build-config ${{ env.build_type }}
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: built
        path: ${{ steps.strings.outputs.build-output-dir }}
    outputs:
      build-path: ${{ steps.strings.outputs.build-output-dir }}
      build-type: ${{ env.build_type }}
      units:      ${{ env.units }}
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
    - name: Import build
      uses: actions/download-artifact@v4
      with:
        name: built
    - name: Run Tests
      run:  >
            IFS=' ' read -r -a array <<< "${{ needs.build-linux.outputs.units }}" &&
            for t in "${array[@]}";
            do
            chmod 700 ${{ needs.build-linux.outputs.build-path }}/${{ needs.build-linux.outputs.build-type }}/Tests/${t}/${t}Tests;
            ${{ needs.build-linux.outputs.build-path }}/${{ needs.build-linux.outputs.build-type }}/Tests/${t}/${t}Tests;
            done
