name: "Build and run"
on:
  push:
    branches:     "master"
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
jobs:
  build-linux:
    name:    Build on linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:   [Debug]
        cpp_compiler: [g++,clang++]
    env:
      units: "board"
    steps:
    - uses:  actions/checkout@v4
    - name:  Set reusable strings
      id:    strings
      shell: bash
      run:   |
             echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    - name:  update catch2 repository
      run:   git clone https://github.com/catchorg/Catch2.git
    - name:  update chess repository
      run:   git clone https://github.com/antlampas/Chess.git
    - name:  Configure CMake
      run:   >
             cmake -B ${{ steps.strings.outputs.build-output-dir }}
             -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
             -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
             -DUNITS="$units"
             -S ${{ github.workspace }}
    - name:  Build
      run:   cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
    - name:  Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
    - name: Run Tests
      run: IFS=' ' read -r -a array <<< "$units" && for t in "${array[@]}"; do ${{ steps.strings.outputs.build-output-dir }}/${{ matrix.build_type }}/Tests/${t}/${t}Tests; done
