name: "Tests"
on:
    push:
        branches: "master"
        paths-ignore:
            - '.github/**'
            - 'LICENSE.md'
            - 'README.md'
    workflow_dispatch:
env:
    units: "board"
jobs:
    build:
        name:    Test
        runs-on: [ubuntu-latest]
        strategy:
            fail-fast: true
            max-parallel: 1
            matrix:
                cpp_compiler: [g++,clang++]
                build_type:   [Debug]
        steps:
        - uses:  actions/checkout@v4
        - name:  Set reusable strings
          id:    strings
          shell: bash
          run: |
               echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        - name:  Configure CMake
          run: >
               cmake -B ${{ steps.strings.outputs.build-output-dir }}
               -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
               -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
               -DUNITS="${{ env.units }}"
               -S ${{ github.workspace }}
        - name:  Build
          run:   cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
        - name:  Test
          working-directory: ${{ steps.strings.outputs.build-output-dir }}
          run:  ctest --build-config ${{ matrix.build_type }}